config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                        sessions: 'sessions',
                        registrations: 'registrations'
                     }

  root 'application#index'

  namespace :admin_panel do
    root 'dashboard#index'
    resources :users
    resources :ads
    resources :comments
  end
end

app/models/admin_panel/ability.rb
module AdminPanel
  class Ability
    include CanCan::Ability

    def initialize(user)
      user ||= User.new

      can :manage, :all if user.admin?
      can :read, :all if user.moderator?
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_closure_tree dependent: :destroy

  # associations
  with_options required: true do |c|
    c.belongs_to :user
    c.belongs_to :ad
  end

  # validations
  validates :content, presence: true
end

app/controllers/admin_panel/ads_controller.rb
module AdminPanel
  class AdsController < BaseController
    include Sortable

    load_and_authorize_resource
    respond_to :html, except: [:update]
    respond_to :json, only:   [:destroy, :update, :create]

    before_action :set_ad, only: [:edit, :update, :destroy]

    def index
      @ads = Ad.includes(:user).order(sortable_query).page(params[:page])
    end

    def show; end

    def edit; end

    def update
      respond_to do |format|
        if @ad.update_attributes(ad_params)
          format.json { render json: { redirect: false, dimmer_message: ad_notice_message('successfully updated') }, status: :accepted }
        else
          format.json { render json: @ad.errors, status: :not_acceptable }
        end
      end
    end

    def destroy
      @ad.destroy
      if params[:redirect_path].present?
        flash[:notice] = ad_notice_message('successfully deleted')
        respond_with(:admin_panel, @ad, location: params[:redirect_path])
      else
        respond_with(:admin_panel, @ad)
      end
    end

    private

    def ad_notice_message(msg)
      "Ad ##{@ad.id} #{msg}"
    end

    def ad_params
      params.require(:ad).permit!
    end

    def set_ad
      @ad = Ad.find(params[:id])
    end
  end
end

app/controllers/admin_panel/base_controller.rb
module AdminPanel
  class BaseController < ActionController::Base
    layout 'admin_panel'
    protect_from_forgery with: :exception

    before_action :authenticate_user!
    before_action :verify_access

    def render_403
      render file: "#{Rails.root}/public/403.html", status: 403, layout: false
    end

    # cancan ability rescue
    rescue_from CanCan::AccessDenied do
      render_403
    end

    def current_ability
      @current_ability ||= AdminPanel::Ability.new(current_user)
    end

    private

    def verify_access
      render_403 if current_user.default_user?
    end
  end
end

app/controllers/admin_panel/comments_controller.rb
module AdminPanel
  class CommentsController < BaseController
    include Sortable

    load_and_authorize_resource
    respond_to :html, except: [:update]
    respond_to :json, only:   [:destroy, :update, :create]

    before_action :set_comment, only: [:edit, :update, :destroy]

    def index
      @comments = Comment.includes(:user, :ad).order(sortable_query).page(params[:page])
    end

    def show; end

    def edit; end

    def update
      respond_to do |format|
        if @comment.update_attributes(comment_params)
          format.json { render json: { redirect: false, dimmer_message: comment_notice_message('successfully updated') }, status: :accepted }
        else
          format.json { render json: @comment.errors, status: :not_acceptable }
        end
      end
    end

    def destroy
      @comment.destroy
      if params[:redirect_path].present?
        flash[:notice] = comment_notice_message('successfully deleted')
        respond_with(:admin_panel, @comment, location: params[:redirect_path])
      else
        respond_with(:admin_panel, @comment)
      end
    end

    private

    def comment_notice_message(msg)
      "Comment ##{@comment.id} #{msg}"
    end

    def comment_params
      params.require(:comment).permit!
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end
  end
end

app/controllers/admin_panel/dashboard_controller.rb
module AdminPanel
  class DashboardController < BaseController
    def index; end
  end
end

app/controllers/admin_panel/users_controller.rb
module AdminPanel
  class UsersController < BaseController
    include Sortable

    load_and_authorize_resource
    respond_to :html, except: [:update]
    respond_to :json, only:   [:destroy, :update, :create]

    before_action :set_user, only: [:edit, :update, :destroy]
    before_action :check_password_params, only: [:update]

    def index
      @users = User.order(sortable_query).page(params[:page])
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          flash[:notice] = user_notice_message('successfully added')
          format.json { render json: { redirect: true, redirect_path: edit_admin_panel_user_path(@user), dimmer_message: user_notice_message('successfully created') }, status: :created }
        else
          format.json { render json: @user.errors, status: :not_acceptable }
        end
      end
    end

    def show; end

    def edit; end

    def update
      respond_to do |format|
        if @user.update_attributes(user_params)
          format.json { render json: { redirect: false, dimmer_message: user_notice_message('successfully updated') }, status: :accepted }
        else
          format.json { render json: @user.errors, status: :not_acceptable }
        end
      end
    end

    def destroy
      @user.destroy
      if params[:redirect_path].present?
        flash[:notice] = user_notice_message('successfully deleted')
        respond_with(:admin_panel, @user, location: params[:redirect_path])
      else
        respond_with(:admin_panel, @user)
      end
    end

    private

    def user_notice_message(msg)
      "User ##{@user.id} #{@user.full_name} #{msg}"
    end

    def user_params
      params.require(:user).permit(:role, :first_name, :last_name, :birthday,
                                   :address, :city, :state, :country, :zip,
                                   :email, :password, :password_confirmation,
                                   :avatar)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def check_password_params
      return if params[:user].present? && params[:user][:password].present?
      params[:user].except!(:password, :password_confirmation)
    end
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
  def active_nav_class(expected, *values)
    values.include?(expected) ? 'active' : ''
  end

  def required_field_class(action)
    %w(new create).include?(action) ? 'required' : ''
  end

  def flash_message(class_name, header_text, messages)
    render partial: 'admin_panel/partials/flash_message', locals: {
      class_name: class_name,
      header_text: header_text,
      messages: messages
    }
  end

  def link_to_back_path(path)
    if params[:link_to_back_path].present?
      params[:link_to_back_path]
    else
      path
    end
  end

  def sortable_link(title, *columns)
    SortableLink.new(title: title, columns: columns, path: request.path, params: params).render
  end
end

app/views/admin_panel/comments/_form.html.haml
= form_for [:admin_panel, @comment], html: { multipart: true }, remote: true, data: { model_name: @comment.class.name.downcase, type: :json } do |f|
  - if @comment.errors.any?
    = flash_message('error', 'An error occurred while attempting to save the recorded steps:', @comment.errors.full_messages)
  .ui.grid.center.aligned
    .eleven.wide.column
      .ui.buttons
        = link_to(link_to_back_path(admin_panel_comments_path), class: 'ui blue labeled icon button js-loading-btn') do
          %i.reply.icon
          Back
        - if @comment.persisted?
          = link_to admin_panel_comment_path(@comment), class: 'ui blue icon button js-loading-btn' do
            Show
          = link_to admin_panel_comment_path(@comment, redirect_path: link_to_back_path(admin_panel_comments_path)), class: 'ui blue right labeled icon button js-loading-btn', method: :delete, data: { confirm: 'The record will be removed' } do
            Delete
            %i.remove.icon
      .ui.form.large.segment
        %h4.ui.dividing.header User and Ad information
        .ui.two.cards
          = render partial: 'admin_panel/users/card', locals: { user: @comment.user, card_style: nil}
          = render partial: 'admin_panel/ads/card', locals: { ad: @comment.ad, card_style: nil }
        %h4.ui.dividing.header Comment information
        .field
          = f.label :content, 'Content'
          .ui.icon.input
            = f.text_area :content, placeholder: 'Content', type: 'text'
        = f.submit 'Submit', class: 'ui blue submit button js-form-send-btn'

app/views/admin_panel/comments/edit.html.haml
- content_for :panel_description do
  = render partial: 'admin_panel/partials/panels_descriptions/comments/edit'
= render 'form'

app/views/admin_panel/comments/index.html.haml
- content_for :panel_description do
  = render partial: 'admin_panel/partials/panels_descriptions/comments/index'

- if notice
  .ui.success.message.segment.center.aligned
    %i.close.icon
    .header= notice

.ui.secondary.menu.container
  .right.menu
    .item
      .ui.icon.input
        %input{ placeholder: 'Search', type: 'text'}/
        %i.search.link.blue.icon

%br/
%table.ui.basic.table.blue
  %thead
    %tr
      %th= sortable_link('#', 'id')
      %th= sortable_link('User', 'users.last_name', 'users.first_name')
      %th= sortable_link('Ad', 'ad_id')
      %th= sortable_link('Content', 'content')
      %th Actions
  %tbody
    - @comments.each do |comment|
      %tr.js-record{ data: { id: comment.id } }
        %td= comment.id
        %td= link_to comment.user.full_name, admin_panel_user_path(comment.user)
        %td= link_to "##{comment.ad.id}", admin_panel_comment_path(comment.ad)
        %td= comment.content.truncate(50)
        %td
          .ui.basic.buttons
            = link_to 'Show', admin_panel_comment_path(comment), class: 'ui basic button js-loading-btn'
            - if can? :manage, Ad
              = link_to 'Edit', edit_admin_panel_comment_path(comment, link_to_back_path: request.fullpath), class: 'ui basic button js-loading-btn'
              .ui.basic.button.js-delete-record-btn{ data: { record_id: comment.id, fullpath: request.path } } Delete
  %tfoot
    %tr
      %th{ colspan: '5' }
        = paginate @comments, theme: 'admin_panel'